### ISSUE TITLE
Attachment actions inputs property incorrectly calling dictionary

### ISSUE THREAD

**Issue by jwa1** [CiscoDevNet/webexteamssdk#102]
Receiving a `TypeError: 'collections.OrderedDict' object is not callable` error when accessing `.inputs` on an `AttachmentAction`.

In mixins/attachment_action.py, on line 73:

`return self._json_data('inputs')` should be `return self._json_data.get('inputs')`

**Comment by sQu4rks** [comment]
+1 ran into the same problem. Accessing the json dict directly works as a work-around

```python
attachment = api.attachment_actions.get(attachment_id)
inputs = attachment._json_data.get('inputs')
```

**Comment by cmlccie** [comment]
Thank you for catching and fixing the bug.  🙂  I will merge the PR.
