### ISSUE TITLE
Get Room Meeting Details missing

### ISSUE THREAD

**Issue by DavCisco** [CiscoDevNet/webexteamssdk#111]
Cannot get the room meeting details with the SDK
it's the endpoint: /v1/rooms/roomId/meetingInfo
ref: https://developer.webex.com/docs/api/v1/rooms/get-room-meeting-details

**Comment by sQu4rks** [comment]
Hi @DavCisco 

we have this on the radar to incorporate. Please see our [Release Plans](https://github.com/CiscoDevNet/webexteamssdk/wiki/Release-Plans) and the tracking issue for missing endpoints(#113) for further details on when and how the "missing endpoints" will be added. 

I'll be adding this endpoint over the weekend.

**Comment by cmlccie** [comment]
@sQu4rks Have you worked on adding this endpoint?  No big deal if you haven't, I will be working on catching up the missing endpoints tomorrow.  I just don't want to duplicate work.  🙂

**Comment by sQu4rks** [comment]
@cmlccie will push a PR for this later today :)

**Comment by DavCisco** [comment]
Thanks guys!

**Comment by sQu4rks** [comment]
PR #130 closed this issue and the functionality will be included in the next release. Thanks to @cmlccie for the implementation and @DavCisco for raising the missing endpoint.
