### ISSUE TITLE
Add TrackingId to ApiError message.

### ISSUE THREAD

**Issue by sQu4rks** [CiscoDevNet/webexteamssdk#112]
Since the tracking id is a great way for the support team to troubleshoot issues what do you think about including it in the error message of the `ApiError`? 

While you can access it via the response property of the `ApiError` this option is only accessible when actually catching the error.

**Comment by cmlccie** [comment]
Great idea.  This will definitely help improve the transparency of the API responses and errors.

I'm on it, and I'd love your feedback.  I'll submit a PR for you to review.

**Comment by sQu4rks** [comment]
I just merged the PR. Closing this issue.
