### ISSUE TITLE
Update the existing Webex Teams API wrappers and data models

### ISSUE THREAD

**Issue by cmlccie** [CiscoDevNet/webexteamssdk#127]
Review the existing Webex Teams API wrappers and data models and ensure they are up-to-date with all posted parameters, attributes, and sub-endpoints published on developer.webex.com.

- [x] Access Tokens API
- [x] Admin Audit Events API
- [x] Attachment Actions API
- [x] Events API
- [x] Guest Issuer API
- [x] Licenses API
- [x] Memberships API
- [x] Messages API
- [x] Organizations API
- [x] People API
- [x] Roles API
- [x] Rooms API
- [x] Teams API
- [x] Team Memberships API
- [x] Webhooks API

**Comment by cmlccie** [comment]
@sQu4rks, I have reviewed and updated all of the existing wrapped APIs ***except*** the Rooms API.  I'll review this one after your PR with the meeting info API endpoint update.

**Comment by sQu4rks** [comment]
@cmlccie The `/rooms` API matches the implementation in the sdk so I think we can, after merging PR #129, close this issue as all endpoints are up to date.
