### ISSUE TITLE
Python2 compatibility generator_containers.py

### ISSUE THREAD

**Issue by dmfigol** [CiscoDevNet/webexteamssdk#57]
I am using the module on IOS XE Guest Shell with python2 only.
This API call fails, because `__qualname__` is available only in Python3.
```
>>> spark_api.rooms.list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/ciscosparkapi/generator_containers.py", line 70, in __repr__
    func_name=self.generator_function.__qualname__,
AttributeError: 'function' object has no attribute '__qualname__'
```

**Comment by cmlccie** [comment]
@dmfigol I have correct this compatibility issue in `ciscosparkapi` v0.10.1 and `webexteamssdk` v1.1.1.  Let me know if you have any issues after updating to these versions.
