### ISSUE TITLE
Suppress exception response message

### ISSUE THREAD

**Issue by dmfigol** [CiscoDevNet/webexteamssdk#62]
Currently exception messages are extremely big.
I propose suppress exception response sent from Spark server, leaving only necessary error message by default. Response could be still accessed as an exception attribute.

**Comment by cmlccie** [comment]
Some people like them.  😎

...but I agree they can be lengthy.  I have had another recent request to enhance the errors.  I'll see what I can do to make these a little cleaner.

**Comment by cmlccie** [comment]
@dmfigol I have released this enhancement in v1.1.  Let me know if you have any feedback on the simplified error messages.
