### ISSUE TITLE
api.rooms.list(type='group') showing direct spaces

### ISSUE THREAD

**Issue by zoneix** [CiscoDevNet/webexteamssdk#64]
```
from webexteamssdk import WebexTeamsAPI

api = WebexTeamsAPI()

all_rooms = api.rooms.list(type='group')

for room in all_rooms:
    print room.title + " " + room.id
    
print len(list(all_rooms))
```

This is listing Group spaces and SOME 1:1 Direct spaces for me!

**Comment by cmlccie** [comment]
Hi @zoneix.

This is/was likely an issue with the Webex Teams APIs themselves.  Are you still experiencing this issue?  If so, I recommend trying the same request using the interactive Webex Teams docs or Postman?  Do the returned results include 1:1 spaces?
