### ISSUE TITLE
Developing Rasa connector using webexteamssdk

### ISSUE THREAD

**Issue by nahidalam** [CiscoDevNet/webexteamssdk#65]
Rasa (https://rasa.com/) is an open source conversational AI platform. I am developing a Webex Teams connector for Rasa. The goal is essentially making Webex Teams as another supported input/output channel for Rasa. Rasa already has connectors for Slack, Facebook etc.

Using `webexteamssdk` and following the code for [Rasa Slack connector](https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/channels/slack.py), I wrote below code so far. Wanted to make sure I am in the right direction. Thoughts?

```
from webexteamssdk import WebexTeamsAPI

class CiscoWebexTeamsBot(WebexTeamsAPI, OutputChannel):
    """A Cisco Webex Teams communication channel"""

    @classmethod
    def name(cls):
        return "Cisco Webex Teams"

    def __init__(self, access_token, ciscowebexteams_room=None):

        self.ciscowebexteams_room = ciscowebexteams_room
        super(CiscoWebexTeamsBot, self).__init__(access_token)


    def send_text_message(self, recipient_id, message):
        recipient = self.ciscowebexteams_room or recipient_id
        for message_part in message.split("\n\n"):
            super(CiscoWebexTeamsBot, self).messages.create(roomId=recipient,text=message_part)
```

**Comment by cmlccie** [comment]
Hi @nahidalam.

I haven't worked with Rasa, but your project sounds interesting.  🙂

Is there a reason that you are sub-classing the `WebexTeamsAPI` class?  With the multiple-inheritance nature of your class, this could cause you some complications in the future.  I would think it better to sub-class `OutputChannel` and just create a `WebexTeamsAPI` instance as a class attribute.  Something like:

```python
from webexteamssdk import WebexTeamsAPI

class CiscoWebexTeamsBot(OutputChannel):
    """A Cisco Webex Teams communication channel"""

    @classmethod
    def name(cls):
        return "Cisco Webex Teams"

    def __init__(self, access_token, ciscowebexteams_room=None):

        self.ciscowebexteams_room = ciscowebexteams_room
        self.api = WebexTeamsAPI(access_token)


    def send_text_message(self, recipient_id, message):
        recipient = self.ciscowebexteams_room or recipient_id
        for message_part in message.split("\n\n"):
            self.api.messages.create(roomId=recipient, text=message_part)
```

**Comment by nahidalam** [comment]
Thanks @cmlccie 

What you said makes more sense and definitely makes it more readable. 

I essentially followed their existing implementation of `slack` connector here https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/channels/slack.py

**Comment by nahidalam** [comment]
Thanks @cmlccie 
The PR got approved last night. https://github.com/RasaHQ/rasa_core/pull/1292#event-1958786295

**Comment by nathy84** [comment]
Hello
Do you have an example code how to use this connector?
