### ISSUE TITLE
Sorting messages old-new?

### ISSUE THREAD

**Issue by DJF3** [CiscoDevNet/webexteamssdk#72]
Team,
api.messages.list returns messages in descending order (creation date)

Messages in the Webex Teams client are displayed in ascending order.

Q: How can I sort the messages?

**Comment by fdemello** [comment]
The API doesn’t have a sort option, the default is “The list sorts the
messages in descending order by creation date.”

You need to sort clientside if you need them sorted some other way.

**Comment by DJF3** [comment]
Ok, that example seems to put all messages in a list first and then sort it. Maybe I'll add that step to convert it to a lists first.
Thanks,
DJ
