### ISSUE TITLE
Audio/video calls [question]

### ISSUE THREAD

**Issue by dbmoderro** [CiscoDevNet/webexteamssdk#73]
Hi! Thank you for webexteamssdk. The demo app works great. Does webexteamssdk
allow to make audio and video calls? Thanks!

**Comment by cmlccie** [comment]
Hi @dbmoderro, yes, it does but to do so you need a UI.  The Webex Teams platform-native clients (iOS, Android, Windows, macOS, etc.) of course provide the ability to make and receive voice and video calls.  If you want to provide voice and video calling through your app, you can use our platform SDKs for [iOS](https://developer.webex.com/docs/sdks/ios),  [Android](https://developer.webex.com/docs/sdks/android), and [Browsers](https://developer.webex.com/docs/sdks/browser).

This webexteamssdk is a community-developed Python SDK that leverages the public Webex Teams APIs documented at https://developer.webex.com, which currently only expose the messaging and administration capabilities of the Webex Teams service.
