### ISSUE TITLE
Add a tests for new GuestIssuer functionality introduced in PR #74

### ISSUE THREAD

**Issue by cmlccie** [CiscoDevNet/webexteamssdk#79]
@sQu4rks awesome job with the Guest Issuer PR.  Thank you for submitting it!

I have merged it in, and I will push a new release with the added functionality shortly.  However, we need to create some test and docs for the new functionality to ensure its reliability and to let other developers know how to use it.  Can you take a run at creating the tests and docs?  I'm glad to edit and review.

**Comment by sQu4rks** [comment]
Thanks for merging. I'll go ahead and create the docs and tests.

**Comment by cmlccie** [comment]
Thank you @sQu4rks !
