### ISSUE TITLE
Messages.get throws 404

### ISSUE THREAD

**Issue by slightcisco** [CiscoDevNet/webexteamssdk#83]
Hi,

I am trying to grab the message contents from a web hook. I grab the message ID out of the POST headers and print to screen. I then do messages.get(ID) and only ever get back a 404. This only happens for rooms not individual chats. I have gone to the API documentation at developer.cisco.com and checked the ID is correct.

I saw error #70 and tried to follow the advice given there and gave delay to my calls, however, there was still no joy. Source is below. Thanks in advance.

```
@app.route('/', methods=['POST'])
def messageHandling():
    json_data = request.data
    # Create a Webhook object from the JSON data
    print(json_data)
    webhook_obj = Webhook(json_data)
    # Get the room details
    room = api.rooms.get(webhook_obj.data.roomId)
    # Get the message details ATM messages.get is bad, and i think it has delay while getting group chat messages
    print(webhook_obj.data.id)
    for x in range(0,5):
        try:
            message = api.messages.get(webhook_obj.data.id)
            break
        except:
            time.sleep(5)
    # Get the sender's details
    person = api.people.get(message.personId)
    me = api.people.me()
    print(me)

    print("NEW MESSAGE IN ROOM '{}'".format(room.title))
    print("FROM '{}'".format(person.displayName))
    print("MESSAGE '{}'\n".format(message.text))
`

**Comment by ransalmo** [comment]
I got a similar error with messages.list().

**Comment by slightcisco** [comment]
If you have a look at error #70 @ransalmo, there is a temporary workaround for message.list(), but not ideal by any means

**Comment by slightcisco** [comment]
I didnt realise that the bot had to be mentioned for it to be able to retrieve messages...
