### ISSUE TITLE
messages.list() "max" [403] Forbidden Error with bot account

### ISSUE THREAD

**Issue by yinghyu** [CiscoDevNet/webexteamssdk#85]
We are now using webexteamssdk to continuously receive messages with a bot account(the access token will not be expired).  It works well at the beginning of receiving messages, But [403] Forbidden Error occurs when the num of mentioned messages increases to be more than 50.

I've learned from a closed issue"All messages in a room always returned by messages.list() method #50" that max parameter specifies the maximum number of items per page ("page size"). It works well with my own account access token with max=5. I don't know why the max can not work in bot account with mentioned people limit.

My example code to receive messages:
```
from webexteamssdk import WebexTeamsAPI
token = "<token>"
my_room = "<room_id>"
api = WebexTeamsAPI(access_token=token)
messages = api.messages.list(roomId=my_room, mentionedPeople="me")
id = 0
for message in messages:
    id = id + 1
    print(message)
    print(id)
```
Some logs of my test:
```
No set of max -> webexteamssdk.exceptions.ApiError: [403] Forbidden
max = 0 - retrieved "mentionedPeople" = 50 -> webexteamssdk.exceptions.ApiError: [403] Forbidden
max=50 - retrieved "mentionedPeople" = 50 -> webexteamssdk.exceptions.ApiError: [403] Forbidden
max=55 - retrieved "mentionedPeople" = 55 -> webexteamssdk.exceptions.ApiError: [403] Forbidden
max=58 - retrieved "mentionedPeople" = 58 -> webexteamssdk.exceptions.ApiError: [403] Forbidden
max=59 - retrieved "mentionedPeople" = 58 -> no error [403]
max=100 - retrieved "mentionedPeople" = 58 -> no error [403]
max=101 - webexteamssdk.exceptions.ApiError: [400] Bad Request - Failed to retrieve rooms
```

**Comment by cmlccie** [comment]
@yinghyu , so the use case here is that you are polling Webex Teams (using the bot's token) for messages where a bot is mentioned, and you are reporting that you are getting `403 - Forbidden Error` when you try to retrieve > 50 messages.

Have you tried making this same request using the interactive API docs and/or a REST client like Postman?

**Comment by cmlccie** [comment]
@yinghyu I am closing this issue as it doesn't look like an issue with the SDK.  If you are still experiencing this issue, I recommend reproducing the issue using another API client (like Postman).  If you encounter the problem with multiple clients, which I suspect will be the case, then I recommend opening a case with [Webex Developer Support](https://developer.webex.com/support).
